import ItemList from "./models/item-list.type";
/**
 * The armors object contains various armor items, each represented as a key-value pair. The keys are the names of the armor items, and the values are objects that define the properties of each armor item.

Each armor item object has properties such as 
- defname, 
- name, 
- price, 
- defense, 
- quantity, 

and boolean properties like 
- isConsumable, 
- isEquippable, 
- isPurchasable, 
- isSellable, 
- isUsable, and isEquipped.

These properties provide information about the armor item such as its name, price, defense value, and whether it can be consumed, equipped, purchased, sold, used, or is currently equipped.
 */
const armors: ItemList = {
  paddedArmor: {
    defname: "paddedArmor",
    name: "Padded Armor",
    price: 50,
    defense: 1,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  lightLeatherArmor: {
    defname: "lightLeatherArmor",
    name: "Light Leather Armor",
    price: 100,
    defense: 2,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  leatherArmor: {
    defname: "leatherArmor",
    name: "Leather Armor",
    price: 250,
    defense: 3,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  studdedLeatherArmor: {
    defname: "studdedLeatherArmor",
    name: "Studded Leather Armor",
    price: 400,
    defense: 4,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  chainShirt: {
    defname: "chainShirt",
    name: "Chain Shirt",
    price: 1000,
    defense: 5,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  scaleMail: {
    defname: "scaleMail",
    name: "Scale Mail",
    price: 1500,
    defense: 6,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  halfPlate: {
    defname: "halfPlate",
    name: "Half Plate",
    price: 2750,
    defense: 7,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  fullPlate: {
    defname: "fullPlate",
    name: "Full Plate",
    price: 6000,
    defense: 8,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  plateArmorOfProtection: {
    defname: "plateArmorOfProtection",
    name: "Plate Armor of Protection",
    price: 10000,
    defense: 10,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  mithrilPlateArmor: {
    defname: "mithrilPlateArmor",
    name: "Mithril Plate Armor",
    price: 18000,
    defense: 12,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  adamantinePlateArmor: {
    defname: "adamantinePlateArmor",
    name: "Adamantine Plate Armor",
    price: 26000,
    defense: 14,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  dragonScaleArmor: {
    defname: "dragonScaleArmor",
    name: "Dragon Scale Armor",
    price: 40000,
    defense: 18,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  plateArmorOfGolem: {
    defname: "plateArmorOfGolem",
    name: "Plate Armor of Golem",
    price: 63000,
    defense: 20,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  plateArmorOfEtherealness: {
    defname: "plateArmorOfEtherealness",
    name: "Plate Armor of Etherealness",
    price: 100000,
    defense: 24,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  plateArmorOfInvincibility: {
    defname: "plateArmorOfInvincibility",
    name: "Plate Armor of Invincibility",
    price: 173000,
    defense: 28,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  plateArmorOfMirroring: {
    defname: "plateArmorOfMirroring",
    name: "Plate Armor of Mirroring",
    price: 280000,
    defense: 32,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
  plateArmorOfPower: {
    defname: "plateArmorOfPower",
    name: "Plate Armor of Power",
    price: 500000,
    defense: 36,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: true,
    isEquipped: false,
  },
};
export default armors;
