import Armor from "./models/armor.type";
import ItemList from "./models/item-list.type";
/**
 * The armors object contains various armor items, each represented as a key-value pair. The keys are the names of the armor items, and the values are objects that define the properties of each armor item.

Each armor item object has properties such as 
type: "armor",
- defname, 
- name, 
- price, 
- defense, 
- quantity, 

and boolean properties like 
- isConsumable, 
- isEquippable, 
- isPurchasable, 
- isSellable, 
- isUsable, and isEquipped.
rarity: "common"

These properties provide information about the armor item such as its name, price, defense value, and whether it can be consumed, equipped, purchased, sold, used, or is currently equipped.
 */
const armors: ItemList<Armor> = {
  paddedArmor: {
    type: "armor",
    defname: "paddedArmor",
    name: "Padded Armor",
    price: 50,
    defense: 1,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "common",
  },
  lightLeatherArmor: {
    type: "armor",
    defname: "lightLeatherArmor",
    name: "Light Leather Armor",
    price: 100,
    defense: 2,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "common",
  },
  leatherArmor: {
    type: "armor",
    defname: "leatherArmor",
    name: "Leather Armor",
    price: 250,
    defense: 3,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "common",
  },
  studdedLeatherArmor: {
    type: "armor",
    defname: "studdedLeatherArmor",
    name: "Studded Leather Armor",
    price: 400,
    defense: 4,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "common",
  },
  chainShirt: {
    type: "armor",
    defname: "chainShirt",
    name: "Chain Shirt",
    price: 1000,
    defense: 5,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "common",
  },
  scaleMail: {
    type: "armor",
    defname: "scaleMail",
    name: "Scale Mail",
    price: 1500,
    defense: 6,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "common",
  },
  halfPlate: {
    type: "armor",
    defname: "halfPlate",
    name: "Half Plate",
    price: 2750,
    defense: 7,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "common",
  },
  fullPlate: {
    type: "armor",
    defname: "fullPlate",
    name: "Full Plate",
    price: 6000,
    defense: 8,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "common",
  },
  paddedArmorUncommon: {
    type: "armor",
    defname: "paddedArmorUncommon",
    name: "Padded Armor +1",
    price: 150,
    defense: 2,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: false,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "uncommon",
  },
  paddedArmorRare: {
    type: "armor",
    defname: "paddedArmorRare",
    name: "Padded Armor +2",
    price: 500,
    defense: 3,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: false,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "rare",
  },
  paddedArmorLegendary: {
    type: "armor",
    defname: "paddedArmorLegendary",
    name: "Padded Armor +3",
    price: 1500,
    defense: 4,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: false,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "legendary",
  },
  paddedArmorEpic: {
    type: "armor",
    defname: "paddedArmorEpic",
    name: "Padded Armor +4",
    price: 3000,
    defense: 5,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: false,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "epic",
  },
  paddedArmorMythic: {
    type: "armor",
    defname: "paddedArmorMythic",
    name: "Padded Armor +4",
    price: 6000,
    defense: 6,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: false,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    rarity: "mythic",
  },
};
export default armors;
