import ItemList from "./models/item-list.type";
import Weapon from "./models/weapon.type";
/**
 * This code defines an object called weapons that represents a list of items.
 *
 * Each item has properties such as
 * - defname,
 * - name,
 * - price,
 * - damage, etc.
 *
 * The object is initialized with several weapons, each represented as a key-value pair, where the key is the weapon name and the value is an object containing the weapon's properties.
 */
const weapons: ItemList<Weapon> = {
  dagger: {
    defname: "dagger",
    name: "Dagger",
    price: 20,
    damage: 4,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    critical: 2,
    type: "weapon",
    rarity: "common",
  },
  axe: {
    defname: "axe",
    name: "Axe",
    price: 35,
    damage: 5,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    critical: 2,
    type: "weapon",
    rarity: "common",
  },
  mace: {
    defname: "mace",
    name: "Mace",
    price: 50,
    damage: 6,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    critical: 2,
    type: "weapon",
    rarity: "common",
  },
  sword: {
    defname: "sword",
    name: "Sword",
    price: 100,
    damage: 7,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    critical: 2,
    type: "weapon",
    rarity: "common",
  },
  battleaxe: {
    defname: "battleaxe",
    name: "Battleaxe",
    price: 175,
    damage: 8,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    critical: 3,
    type: "weapon",
    rarity: "common",
  },
  warhammer: {
    defname: "warhammer",
    name: "Warhammer",
    price: 220,
    damage: 9,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    critical: 3,
    type: "weapon",
    rarity: "common",
  },
  longsword: {
    defname: "longsword",
    name: "Longsword",
    price: 400,
    damage: 10,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: true,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    critical: 3,
    type: "weapon",
    rarity: "common",
  },
  daggerUncommon: {
    defname: "daggerUncommon",
    name: "Dagger +1",
    price: 60,
    damage: 5,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: false,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    critical: 2,
    type: "weapon",
    rarity: "uncommon",
  },
  daggerRare: {
    defname: "daggerRare",
    name: "Dagger +2",
    price: 180,
    damage: 6,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: false,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    critical: 2,
    type: "weapon",
    rarity: "rare",
  },
  daggerLegendary: {
    defname: "daggerLegendary",
    name: "Dagger +3",
    price: 550,
    damage: 7,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: false,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    critical: 2,
    type: "weapon",
    rarity: "legendary",
  },
  daggerEpic: {
    defname: "daggerEpic",
    name: "Dagger +4",
    price: 1000,
    damage: 8,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: false,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    critical: 2,
    type: "weapon",
    rarity: "epic",
  },
  daggerMythic: {
    defname: "daggerMythic",
    name: "Dagger +5",
    price: 2000,
    damage: 9,
    quantity: 0,
    isConsumable: false,
    isEquippable: true,
    isPurchasable: false,
    isSellable: true,
    isUsable: false,
    isEquipped: false,
    critical: 2,
    type: "weapon",
    rarity: "mythic",
  },
};
export default weapons;
